CREATE TABLE "user" (
  "id" VARCHAR (255) PRIMARY KEY NOT NULL,
  "email" VARCHAR (255) NOT NULL,
  "password" TEXT,
  "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
  "updated" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT TIMEZONE('utc'::text, NOW())
);
